### PR TITLE
rework mnist for layer api changes

### PR DESCRIPTION
**Pull request by brettkoonce**
@rxwei is this the correct idea?  if you like this approach, happy to redo the vision models!

running this on my lowly 2080ti here produces this error, am I doing something wrong?
recompiling then will test w/ cpu mode as well.

```
>swift run MNIST
Reading data.
Constructing data tensors.
[Epoch 1] Loss: 926.598, Accuracy: 55181/60000 (0.91968334)
Fatal error: OOM when allocating tensor with shape[100,32,26,26] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc: file /home/skoonce/swift/swift-source/swift/stdlib/public/TensorFlow/CompilerRuntime.swift, line 2090
Current stack trace:
0    libswiftCore.so                    0x00007fa96a320c80 _swift_stdlib_reportFatalErrorInFile + 115
1    libswiftCore.so                    0x00007fa96a26983c <unavailable> + 3012668
2    libswiftCore.so                    0x00007fa96a26992e <unavailable> + 3012910
3    libswiftCore.so                    0x00007fa96a0b0752 <unavailable> + 1206098
4    libswiftCore.so                    0x00007fa96a236252 <unavailable> + 2802258
5    libswiftCore.so                    0x00007fa96a0afb99 <unavailable> + 1203097
6    libswiftTensorFlow.so              0x00007fa969396442 <unavailable> + 554050
7    libswiftTensorFlow.so              0x00007fa969394b90 checkOk(_:file:line:) + 508
8    libswiftTensorFlow.so              0x00007fa9693b8b70 _TFCCheckOk(_:) + 81
9    libswiftTensorFlow.so              0x00007fa9693b8b60 _swift_tfc_CheckOk + 9
Illegal instruction (core dumped)
```

### CODE REVIEW

**Comment by rxwei** [comment]
> running this on my lowly 2080ti here produces this error, am I doing something wrong?

It's our existing memory leak problem. Sorry!

**Comment by rxwei** [comment]
Would you like to help migrate other models?

**Comment by brettkoonce** [comment]
happy to do cifar/resnet if that helps!  not sure how much work the others would be, but could look into them after?

**Comment by brettkoonce** [comment]
> Would you like to help migrate other models?

happy to do cifar/resnet if that helps! not sure how much work the others would be, but could look into them after?

**Comment by rxwei** [comment]
Helping with cifar/resnet sounds great! The v0.3 release candidate deadline is tomorrow EOD. I'll add other models to my queue for now.

**Comment by rxwei** [comment]
The v0.3 deadline need not block models, but it would be great to see if there's any problem running existing models against new APIs before the deadline.

**Comment by brettkoonce** [comment]
kk, i've got a little bit of spare time let me see what i can do! 🕺

**Comment by rxwei** [comment]
Thanks so much!

**Pull request merged**
