### PR TITLE
Add final image to DCGAN README

### PR DESCRIPTION
**Pull request by rickwierenga**

### CODE REVIEW

**Comment by Shashi456** [comment]
Can you locally check if the image is rendered in the readme? The images are currently broken links.

**Comment by rickwierenga** [comment]
Weird, it works here: https://github.com/rickwierenga/swift-models/tree/master/DCGAN.

`git status` did not see the files locally either, so I had to `git add --force` them. Not sure why that happens. I have checked removing the `.` in `.github` but that did not make a difference.

**Comment by rickwierenga** [comment]
I can view it here too: https://github.com/tensorflow/swift-models/blob/c726c649995644766b16700c49292e2737bbd4d5/DCGAN/.github/result.png

**Comment by Shashi456** [comment]
@rickwierenga alright cool, thanks.

**Comment by rickwierenga** [comment]
The README can be viewed here: https://github.com/tensorflow/swift-models/blob/c726c649995644766b16700c49292e2737bbd4d5/DCGAN/README.md. I'm not sure why it doesn't work here: 
`https://github.com/tensorflow/swift-models/pull/269/commits/c726c649995644766b16700c49292e2737bbd4d5short_path=c028b35#diff-c028b353e265eed8b4734fc37ac5e4cd`. (in code to avoid automatic collapsing)

**Pull request merged**
