### PR TITLE
Move BytePairEncoder to ModelSupport

### PR DESCRIPTION
**Pull request by texasmichelle**
Move out of Model/Text to avoid circular dependencies caused by usage in datasets
Rename file to match struct name

### CODE REVIEW

**Comment by texasmichelle** [comment]
I think this is necessary in order to use LanguageModelDataset with GPT2, since the dataset stores byte pair encoded indexes.

**Comment by texasmichelle** [comment]
Is there a way to surface CMake errors before running kokoro? I don't get any failures locally with `swift test`.

**Comment by BradLarson** [comment]
For surfacing CMake issues, Saleem just added some sample commands to [the Readme](https://github.com/tensorflow/swift-models) and I used those once to test things. However, I'm still forgetting things that CI surfaces, so I'm still not great at it.

**Comment by texasmichelle** [comment]
Ah, that's right - thanks for pointing me to the CMake test instructions.

**Pull request merged**
