### PR TITLE
[BERT] Rename custom embedding layer

### LINKED ISSUE #493: [BERT] Rename custom Embedding layer
BERT uses a [custom `Embedding` layer](https://github.com/tensorflow/swift-models/blob/master/Models/Text/Embeddings.swift), which causes ambiguity errors when other models attempt to use the [standard version](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Layers/Embedding.swift).

```
error: 'Embedding' is ambiguous for type lookup in this context
  private func setEmbedding(_ embedding: inout Embedding<Float>, to p: EmbeddingParameters) {
                                               ^~~~~~~~~
TensorFlow.Embedding:1:15: note: found this candidate
public struct Embedding<Scalar> : Module where Scalar : TensorFlowFloatingPoint {
              ^
/usr/local/google/home/michellecasbon/repos/texasmichelle/swift-models/Models/Text/Embeddings.swift:21:15: note: found this candidate
public struct Embedding<Scalar: TensorFlowFloatingPoint>: Module, Regularizable {
              ^
```

Identify the differences and rename this version accordingly. If appropriate, request changes in swift-apis.

### PR DESCRIPTION
**Pull request by texasmichelle**
Fixes #493

Change filename and all references.

### CODE REVIEW

**Comment by xihui-wu** [comment]
Thanks for the nice cleanup! Can you explain a bit the reason calling it RegularizableEmbedding?

**Comment by texasmichelle** [comment]
I'm not convinced it's the best name, but it's better than `EmbeddingBERT` (as an analog to [`EmbeddingGPT2`](https://github.com/tensorflow/swift-models/blob/master/Models/Text/GPT2/TransformerLM.swift#L294) 😆 
I chose this because it differs from the standard `Embedding` in conformance to [`Regularizable`](https://github.com/tensorflow/swift-models/blob/master/Models/Text/WeightDecayedAdam.swift#L18).

**Comment by xihui-wu** [comment]
I see. That's good for now. Do you have a sense later how to organize Embedding, RegularizableEmbedding and EmbeddingBERT these three ?

**Comment by texasmichelle** [comment]
Ideally, they both use the standard `Embedding`, which may mean adding functionality to the core library. Not something I want to tackle right now, but it's for sure part of #434.

**Pull request merged**
